# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataStorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'Static'
  pod 'Log'
  pod 'Gloss'
  pod 'Eureka'
  pod 'RealmSwift'
  
  # Pods for DataStorage

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end