# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'examples06' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Gloss'
  pod 'PureLayout'
  pod 'Log'
  pod 'Static', git: 'https://github.com/venmo/Static'
  pod 'SDWebImage'

end
