# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lection02' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lection02	
  pod 'PureLayout'

  target 'Lection02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lection02UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
